---
title: "My Awesome Title"
date: 2019-02-22
---
title: A Blog on GitHub. Really?
author: Rich Richardson, a novice GitHub User
email: colanetbiz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle
github_username:  colanetbiz

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

Let's change the `_config.yml` so it's a perfect fit for your new blog. First, we need to use a blog-ready theme. For this activity, we will use a theme named `minima`.

    1. Navigate to the **Code** tab of this repository, and browse to the `_config.yml` file.

    2. In the upper right corner, click pencil2 to open the file editor.

    3. Change `theme:` to **minima** and modify the other configuration variables such as `title:`, `author:`, and `description:` to customize your site.

    4. Click **Create a new branch for this commit and start a pull request**.

    5. Open a pull request.
